---
nxlog/pcre-8.35.tar.gz:
  object_id: c2b6bdbd-5c07-4b85-bd46-3df93916432f
  sha: !binary |-
    NWEwZWZjNzMzMmM2NzQxMTE0MzcyMDIwYTYwYWNmZWQyMmJlZmNiOQ==
  size: 1996552
nxlog/openssl-1.0.1h.tar.gz:
  object_id: fc636975-d756-405a-b628-fa3896874cb5
  sha: !binary |-
    YjIyMzk1OTljOGJmOGY3ZmM0ODU5MGE1NTIwNWMyNmFiZTU2MGJmOA==
  size: 4475692
nxlog/expat-2.1.0.tar.gz:
  object_id: 73d566b0-dc09-4266-a082-f925ac41069e
  sha: !binary |-
    YjA4MTk3ZDE0NjkzMGE1NTQzYTdiOTllODcxY2JhM2RhNjE0ZjZmMA==
  size: 562616
nxlog/nxlog-ce-2.8.1248.tar.gz:
  object_id: 7acd622e-bd87-46ba-b393-773460224586
  sha: !binary |-
    OTFmMTg3Y2VjMTQxODE5Y2Y0NmY0NDg0MThlNTgxOGZiNjhiNGQzOA==
  size: 2552618
nxlog/apr-1.5.1.tar.gz:
  object_id: 8f81cd00-6ef1-41d3-a91c-9407aedecc0e
  sha: !binary |-
    OWNhYTgzZTNmNTBmM2FiYzlmYWI3YzRhM2YyNzM5YTEyYjE0YzNhMw==
  size: 1020833
