meta:
  environment: nxlog-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: nxlog
    networks:
      - name: nxlog1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: nxlog1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.29.0/30
    reserved:
    - 10.244.29.1
    static:
    - 10.244.29.2

  - cloud_properties:
      name: random
    range: 10.244.29.4/30
    reserved:
    - 10.244.29.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.29.8/30
    reserved:
    - 10.244.29.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.29.12/30
    reserved:
    - 10.244.29.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.29.16/30
    reserved:
    - 10.244.29.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.29.20/30
    reserved:
    - 10.244.29.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.29.24/30
    reserved:
    - 10.244.29.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.29.28/30
    reserved:
    - 10.244.29.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.29.32/30
    reserved:
    - 10.244.29.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.29.36/30
    reserved:
    - 10.244.29.37
    static: []
