meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: logstash_shipper_z1
    template: logstash-shipper
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    update:
      canaries: 10
    properties: {}

networks: (( merge ))

properties: {}
